### PR TITLE
feat!: The `subdir` argument to `root_criterion()` must have length one

### LINKED ISSUE #84: `subdir` concept seems flawed
The documentation of `root_criterion()` [says](https://rprojroot.r-lib.org/reference/root_criterion.html) about param `subdir`:

> Subdirectories to start the search in, if found

Note: *Subdirectories*, plural.

But the code only considers the first existing subdirectory.

Excerpt from `find_root()`:

https://github.com/r-lib/rprojroot/blob/1019ad3b34aa302e39b0d24774e0da315f4b8edd/R/root.R#L92

and from `get_start_path()`:

https://github.com/r-lib/rprojroot/blob/1019ad3b34aa302e39b0d24774e0da315f4b8edd/R/root.R#L122-L124

Or did I misinterpret something?

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #84.

### CODE REVIEW

**Comment by krlmlr** [comment]
@salim-b: Testing the implications of disallowing `subdir` with length > 1.

**Comment by krlmlr** [comment]
Not needed.

**Comment by salim-b** [comment]
> Not needed.

Just out of curiosity: What's your conclusion from this PR? What do you mean exactly by "not needed"?

**Comment by krlmlr** [comment]
More than that: it's a regression and harmful, the current behavior is necessary for `is_testthat` to work with `R CMD check` .

**Comment by salim-b** [comment]
Ok, thanks for clarifying ☺️

**Pull request closed without merging**
