### PR TITLE
feat: Add `is_quarto_project` criterion

### LINKED ISSUE #91: FR: Add Quarto criterion
Look for _quarto.yml?
There is Quarto blog / book and soon manuscipts project types.

If you think it is relevant, I can try opening a PR.

### PR DESCRIPTION
**Pull request by olivroy**
Fix #91 
This PR also fixes some warnings with mockr.

Note that I was not able to load with load_all() on Windows
```r
<error/rlang_error>
Error in `pkgload::load_all()`:
! Namespace for rprojroot can't already exist.
---
Backtrace:
    ▆
 1. └─pkgload::load_all()
 2.   └─pkgload:::create_ns_env(path)
 3.     └─cli::cli_abort(...)
 4.       └─rlang::abort(...)
 ```

Edit: I also forgot to create this PR from a branch.. 

Reference: https://quarto.org/docs/projects/quarto-projects.html

### CODE REVIEW

**Comment by krlmlr** [comment]
My last action probably messed up your local clone, fix with `git fetch && git rebase` .

**Comment by olivroy** [comment]
I will reopen on a branch!

**Comment by olivroy** [comment]
It is fine. Does the implementation look ok to you?

**Comment by krlmlr** [comment]
Thanks, looks good! I'll merge the next time I work on this package.

**Pull request merged**
