### PR TITLE
Return absolute paths unchanged

### PR DESCRIPTION
**Pull request by krlmlr**
If the first component is already an absolute path, everything is returned unchanged. This applies to `find_root_file()` and the criteria's "member functions".

Fixes https://github.com/r-lib/here/issues/34, fixes https://github.com/r-lib/here/issues/31.

Closes #46.

@jthurner @StevenMMortimer @czeildi @lgaborini: Would that make {here} easier to use?

@yihui: What do you think about this approach for handling paths that are already absolute, in {here} and {rprojroot}?

### CODE REVIEW

**Comment by StevenMMortimer** [comment]
@krlmlr Makes sense and seems to be a great solution to dealing with a combination of absolute and relative paths. Thanks for working on it!

**Comment by jthurner** [comment]
@krlmlr 
Yes, much better fix for r-lib/here#34 and r-lib/here#31 than my PR. Thanks!

**Comment by czeildi** [comment]
Looks great, thanks a lot for your work, this will definitely improve my workflow.

**Comment by krlmlr** [comment]
Thanks for your feedback!

**Comment by lgaborini** [comment]
Looking good! Thanks!

**Comment by yihui** [comment]
@krlmlr That makes sense to me. Thanks!

**Pull request merged**
