### PR TITLE
add `is_pkgdown_project` root criterion

### PR DESCRIPTION
**Pull request by salim-b**
looking for a `_pkgdown.yml`, `_pkgdown.yaml`, `pkgdown/_pkgdown.yml` and/or `inst/_pkgdown.yml` file

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks! I'll pick it up when I next work on rprojroot/here.

**Comment by jennybc** [comment]
What's the scenario where the above makes something recognizably a project and no other existing criterion does?

Am I just failing to see a usage pattern that I happen not to share?

**Comment by salim-b** [comment]
@jennybc  I'd simply like to have a standardized way to check if a specific directory is set up for pkgdown. I could use it e.g. as follows:

```r
is_pkgdown_dir <- function(path = ".") {
  rprojroot::is_pkgdown_project$testfun %>%
      purrr::map_lgl(~ .x(path = path)) %>%
      any()
}
```

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
